name: planner_assistant
description: A web app for creating and optimizing plans for projects

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: "^2.17.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.2

  google_fonts: ^3.0.1 
  path_provider: ^2.0.2
  json_annotation: ^4.0.1
  url_launcher: ^6.1.6
  flutter_riverpod: ^2.1.1
  intl: ^0.17.0
dev_dependencies:
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4
  flutter_lints: ^2.0.1
  build_web_compilers: ^3.2.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: M PLUS Rounded 1c
      fonts:
        - asset: fonts/MPLUSRounded1c-Regular.ttf
        - asset: fonts/MPLUSRounded1c-Bold.ttf
          weight: 700
    - family: Noto Sans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf
        - asset: fonts/NotoSans-Italic.ttf
          style: italic
        - asset: fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: fonts/NotoSans-BoldItalic.ttf
          weight: 700
          style: italic
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic


